name: symphony_desktop
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audio_video_progress_bar: ^2.0.3
  audiotagger: ^2.2.1
  bitsdojo_window: ^0.1.5
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.2
  flutter_acrylic: ^1.1.4
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  ionicons: ^0.2.2
  media_kit: ^1.1.11
  media_kit_libs_audio: ^1.0.5
  responsive_grid: ^2.2.0
  responsive_grid_list: ^1.3.2
  text_scroll: ^0.2.0
  youtube_explode_dart: ^2.3.1
  data_table_2: ^2.5.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

assets:
  - assets/icon.png

flutter_icons:
  image_path: "assets/icon.png"
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png"
